POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "this is a blog title",
    "author": "this is a blog author",
    "url":  "this is a blog url",
    "likes": 0,
    "userId": "65857257768d3b56cbc8d8c4"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "this is a blog title",
    "author": "this is a blog author",
    "url":  "this is a blog url",
    "likes": 0,
    "userId": "658574cf768d3b56cbc8d8db"
}